# -*- coding: utf-8 -*-
"""exp2.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19gI-r7Ker_uI_CFc98Xz3yMMr_d5H_Aa
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing(as_frame=True)
df = housing.frame
X = df[['AveRooms']].values
y = df['MedHouseVal'].values.reshape(-1,1)
X_b = np.c_[np.ones((len(X),1)), X]

theta_normal = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y
y_pred_normal = X_b @ theta_normal

print("----- Normal Equation -----")
print("Intercept :", theta_normal[0][0])
print("Slope     :", theta_normal[1][0])
print("MSE        :", mean_squared_error(y,y_pred_normal))
print("R2 Score   :", r2_score(y,y_pred_normal))
print("---------------------------")
print()

def compute_cost(X, y, theta):
    m = len(y)
    predictions = X @ theta
    cost = (1 / (2 * m)) * np.sum((predictions - y) ** 2)
    return cost

def gradient_descent(X, y, theta, learning_rate, iterations):
    m = len(y)
    cost_history = []
    for i in range(iterations):
        gradients = (1 / m) * X.T @ (X @ theta - y)
        theta = theta - learning_rate * gradients
        cost_history.append(compute_cost(X, y, theta))
    return theta, cost_history

theta = np.zeros((2,1))
learning_rate = 0.001
iterations = 1000

theta_gd, cost_history = gradient_descent(
    X_b,
    y,
    theta,
    learning_rate,
    iterations
)
y_pred_gd = X_b @ theta_gd

print("\n----- Gradient Descent -----")
print("Intercept :", theta_gd[0][0])
print("Slope     :", theta_gd[1][0])
print("MSE       :", mean_squared_error(y, y_pred_gd))
print("R2 Score  :", r2_score(y, y_pred_gd))
sort_index=np.argsort(X.flatten())

plt.figure(figsize=(8,5))

plt.scatter(X,y,s=10,color='blue',label='Actual Data')

plt.plot(X[sort_index],
         y_pred_normal[sort_index],
         color='red',
         linewidth=2,
         label='Normal Equation')

plt.plot(X[sort_index],
         y_pred_gd[sort_index],
         color='green',
         linewidth=2,
         label='Gradient Descent')

plt.xlabel("Average Number of Rooms")
plt.ylabel("Median House Value")
plt.title("Linear Regression")
plt.legend()
plt.show()