# -*- coding: utf-8 -*-
"""exp3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vK5zSLr6Iwnvriz2BWcnaSWwKxU9HpK9
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

data = {
    'Age':[10,5,8,2,1,3,2,4,1,2],
    'Distance':[5,3,4,2,1,2,1,3,2,1],
    'price':[250,320,340,450,600,650,700,720,800,850]
}
df=pd.DataFrame(data)
print("\nDATASET\n")
print(df)
x=df[['Age','Distance']]
y=df['price']
model=LinearRegression()
model.fit(x, y) # Fit the model to the data
print("\nModel parameters\n")
print("Intercept:")
print(model.intercept_)
print("Coefficients:")
for feature,coef in zip(x.columns,model.coef_):
    print(feature, ":", coef)

print("\nREGRESSION EQUATION\n")
equation = "price = "
for feature, coef in zip(x.columns, model.coef_):
    equation += f"({coef:.4f} * {feature}) + "
equation += f"{model.intercept_:.4f}"
print(equation)

y_pred = model.predict(x) # Define y_pred

mse=mean_squared_error(y,y_pred)
r2=r2_score(y,y_pred)
print("\nModel Evaluation\n")
print("Mean Squared Error (MSE)", round(mse,4))
print("R^2 score:",round(r2,4))
new_house=pd.DataFrame({
    'Age':[2],
    'Distance':[2]
}) # Correct new_house columns
predicted_price=model.predict(new_house)
print("\n NEW HOUSE PREDICTION\n")
print("predicted House_price.",
      round(predicted_price[0],2))
plt.figure(figsize=(8,6))
plt.scatter(y,y_pred,color='blue')
plt.plot([y.min(),y.max()],
         [y.min(),y.max()], # Add missing comma
         color='red')
plt.title('Actual vs Predicted House Prices')
plt.grid(True) # Correct 'true' to 'True'
plt.show()